### ISSUE TITLE
[MPI_WP2]: 7. ReSources

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/ReSources#54]
- **For the app ReSources, the data tables to be displayed** now to be stored in GitHub (fixed location/name but updatable) as csv files. The pending list will be populated from a text file or by reading a directory.
  - Continuation: -> https://github.com/Pandora-IsoMemo/data-tools/issues/56

- **If, a covariate model is defined with a numeric variable** make the option available to display a smoothed plot showing a credible interval range like in PlotR. (code from this not to be used and here mentioned only as an example).
This is done under “Output” -> “Display by”
If under the option above the user selects a numeric variable then under “Select plot type” the user can select “Smoothed plot”. The credible ranges are selected in the scroll inputs at the bottom left.
The figure below shows the input for a numeric variable and how it is selected:

   ![Image](https://user-images.githubusercontent.com/73887426/183870447-e2feb0c4-1527-4d4f-a17e-d98f2897074a.png)

   To exemplify add the inputs/selection above to the “Five_source_example_model”. 
Run the model! The options within the red rectangle allow the user to select different ways of displaying the results for covariates and their interactions. These are shown as credible intervals (box plots) or histograms, for instance. The option to show these box plots/histograms/ results for numeric categories should have been included but this is missing! They should be added!
In addition, one can select an option to have the numeric inputs in the x-axis and estimates in the y-results as smoothed graphs. This implies that ggplot2 should be used (options: loess; ksmooth, or gam). User gives as inputs the x values and the y credible intervals. The user can then select to display the different estimates for the numeric covariates in a similar manner as
currently implemented for covariate. Example from PlotR assuming that one adds two dietary estimates:

   ![Image](https://user-images.githubusercontent.com/73887426/183870815-505beb87-1fd1-4b44-8382-4d0385bc8c1b.png)

   The differences between the implementation in PlotR (only given as an example) and the
future ReSources implementation:

   - Only one x-axis
   - Only one y-axis
   - No intervals shown just the envelopes
   - The envelopes should be colored with some transparency (for when plots overlap). User pick transparency level.
   - User can select which individuals plots to have visible 

- **Other Resource tasks:**
  - [x] User can select the x and y axes ranges to be displayed for Model diagnostic plots (Trace, AutoCor). 
  - [x] Rename AutoCor as AutoCorr -> #92
  - [x] Rename “Model diagnostic plots” as “Convergence plots” -> #92
  - [x] Separate “Goodness-of-Fit measures” into two tabs to be named “Convergence tests” and “Information criteria”. The options under the current “Goodness-of-Fit measures” are displayed as they are but p-value, wAIC, and BIC are moved to “Information criteria” whereas the remainder become part of “Convergence tests” -> #92
   - [x] When saving a model its default name should be “model.zip” and if the model was previously loaded the default name should be that of the loaded model. A reset returns the default name to “model.zip”
   - [x] For the different tables in data input have check boxes to signal if during the pasting of data the first row and/or column are included. Currently it is assumed that these are included but I want to give the option of choosing.
   - [x] #120
   - [x] Option to rotate x or y text labels in results graphs by a certain degree value
     - [x] implement in shinyTools
     - [x] embed into resources
   - [x] Currently the user can select hyperparameter values but only one input is available (Source contribution distribution option Dirichlet). This means that all hyperparametervalues for the different food sources are the same. Allow the user to set these individually.
   - [x] If the number of food sources is changed after these are set then reset their values to 1

   ![Image](https://user-images.githubusercontent.com/73887426/183871312-9b109993-8eac-4dd4-a321-ce161d5354f6.png)

   - [x] Update the interface for up/downloading model objects. After adding the option for model object up-/download, we have some redundancy with the existing input to: “Select example model”. Rework the UI as suggested in: https://github.com/Pandora-IsoMemo/resources/issues/23. When updating this part of the app, add new checks and fix bugs related to missing updates of inputs when uploading a model. Use frames where needed and where possible.

**Comment by arunge** [comment]
@isomemo There are two left open points from [above](https://github.com/Pandora-IsoMemo/ReSources/issues/54#issue-1334357026)
1. the default y range for all ReSources results graphs (with boxplots and future smoothed curves) should be between 0 and 100%
2. the “Smoothed plot”

Regarding: 
1. we discussed today that default ranges should only be changed to 0-100% for
  - Source contributions
  - Component contributions
  - Source contributions `<*>`
  - User Estimate newEst

2. Currently it is possible to export data of estimates and uncertainties under _Summary statistics_:
  ![image](https://github.com/Pandora-IsoMemo/ReSources/assets/16759098/67a4dbf3-8d16-484e-9165-3cb1759ce877)
  This file could be used to create a smoothed plot with PlotR. 
  - We could add a button that opens PlotR
  - What might be missing in PlotR is 
    - the option to filter data in order to create smoothed plots for a single group of data.
  - multiple axis can be hidden in PlotR
  - transparency of uncertainty can already be displayed in PlotR
    ![image](https://github.com/Pandora-IsoMemo/ReSources/assets/16759098/d8c9da31-954d-4e7f-bdcf-ac1f1b4c8488)

  Please let us discuss next time which way to take respecting the effort!

**Comment by isomemo** [comment]
@arunge it would be more efficient to discuss this during our next meeting!

**Comment by arunge** [comment]
@isomemo As discussed, I added the option to draw a smooth line (1, 2) with version Resources 24.07.0 using the `method` parameter of `ggplot2::geom_smooth()`.

![image](https://github.com/Pandora-IsoMemo/ReSources/assets/16759098/8f0e42b3-0b2b-4b3e-a2d6-0f124590b72b)

However, I had to add the option to select a "smoothing method" and needed to set "Linear Model" as default value. When loading the examples, running the model and drawing the plots, there are several plots containing only two or three data points. The "Locally Weighted Scatterplot Smoothing" (`method = "loess"`) requires more than 3 data points and might fail for very few data and a too low value of smoothing (`span`) which always leads to warnings that pop up.

Please let me know, if you have questions or remarks!

**Comment by isomemo** [comment]
@arunge if it fails due to low data can we add our own error message?

**Comment by arunge** [comment]
@isomemo This I am already doing:
- the default value is the "Linear Model" to avoid warnings when starting the app with the test-model
- if one still tries to use "loess" following custom error occurs:
  ![image](https://github.com/user-attachments/assets/44468459-d2ce-4f33-8506-d0e5f5078e42)

**Comment by isomemo** [comment]
@arunge perfect! thanks!

**Comment by arunge** [comment]
@isomemo Ok, thanks. Then I am closing here.
